import { IUser } from "../../controllers/userController/create/createUser";

export const usersArray: Array<IUser> = [
        {   
            id: 1,
            gender:"Male",
            name:"Ricky",
            age: 30,
            occupation: "Conman",
            catchphrase: "'Gotta learn stuff through denial and error.'",
            photo:"https://i.imgur.com/NtvmDPX.gif",
            first_connection: ['Julian', 'Bubbles', 'Ray', 'Adam'],
            second_connection: ['Mr.Lahey', 'Randy'],
            third_connection: ['Barb Lahey'],
        },
        {  
            id: 2,
            gender:"Male",
            name:"Julian",
            age: 32,
            occupation:"Master Mind Criminal",
            catchphrase: "'Life isn't about geating chicken fingers all the time.'",
            photo:"https://media.giphy.com/media/aOWrdfc6nNdxC/giphy.gif",
            first_connection: ['Ricky', 'Bubbles', 'Adam'],
            second_connection: ['Ray', 'Mr.Lahey', 'Randy'],
            third_connection: ['Barb Lahey'],
        },
        {   
            id: 3,
            gender:"Male",
            name:"Bubbles",
            age: 31,
            occupation:"Kitty Tamer and Shopping Cart Repairman",
            catchphrase:"'That is one Nice Kitty.'",
            photo:"https://lh4.googleusercontent.com/-MZqdve1pHkg/Ua8_VDP8aLI/AAAAAAAAEpE/6smdW-4hWWQ/w400-h289-no/Trailer+Park+Boys+GIF+%25285%2529.gif",
            first_connection: ['Ricky', 'Julian', 'Adam'],
            second_connection: ['Ray', 'Mr.Lahey', 'Randy'],
            third_connection: ['Barb Lahey'],
        
        },
        {   
            id:4,
            gender: "Male",
            name: "Mr.Lahey",
            age: 57,
            occupation:"Trailer Park Supervisor",
            catchphrase:"'I am the Trailer Park Supervisor.'",
            photo:"https://media1.tenor.com/images/8c13cbb01c9db3a094cdb4d791be82b2/tenor.gif?itemid=8836984",
            first_connection: ['Barb Lahey', 'Randy'],
            second_connection: ['Ricky', 'Bubbles', 'Julian', 'Adam'],
            third_connection: ['Ray'],
        },
        {   
            id:5,
            gender:"Male",
            name:"Randy",
            age: 30,
            occupation:"Assistant Trailer Park Supervisor",
            catchphrase:"'Ive got some cheeseburgers.'",
            photo: "https://thumbs.gfycat.com/IlliterateMemorableCurlew-size_restricted.gif",
            first_connection: ['Mr.Lahey', 'Barb Lahey'],
            second_connection: ['Ricky', 'Bubbles', 'Julian', 'Adam'],
            third_connection: ['Ray'],
        },  
        {   id:6,
            gender:"Male",
            name:"Ray",
            age: 55,
            occupation:"Truck Driver",
            catchphrase:"'That's the way she goes.'",
            photo:"https://i.redd.it/xlcncm28yo7z.gif",
            first_connection: ['Ricky'],
            second_connection: ['Bubbles', 'Julian'],
            third_connection: ['Mr.Lahey', 'Barb Lahey', 'Randy', 'Adam'],
        },
        {   
            
            id:7,
            gender:"Female",
            name:"Barb Lahey",
            age: 56,
            occupation:"Trailer Park Owner",
            catchphrase:"'Randy, put a shirt on.'",
            photo:"https://i.pinimg.com/236x/4a/ab/df/4aabdf740f7ddf92d96adb5afca15b76.jpg",
            first_connection: ['Mr.Lahey', 'Randy'],
            second_connection: ['Bubbles', 'Julian', 'Ricky'],
            third_connection: ['Ray', 'Adam'],
        }
];