export const technicalSkills: { [key: string]: Array<string> } = {
    Languages: [
        "JavaScript",
        "TypeScript",
        "C#",
        "Java",
        "Python",
        "Bash",
        "Powershell",
        "GraphQL",
    ],
    FrontendSkills: [
        "React",
        "Angular",
        "Jest Testing",
        "React Bootstrap",
        "BootStrap",
        "Mobx",
        "Highcharts",
        "Context API",
        "Sass",
        "HTML 5",
        "CSS3",
        "Redux",
        "Mobile First/Responsive Design",
        "Styled Components (CSS in JS)",
    ],
    BackendSkills: [
        "Node.js",
        "Express",
        "GraphQL",
        "Postman",
        "PostgreSQL",
        "Oracle19c",
        "SOAP UI",
        "Heroku",
        "Hasura",
        "RabbitMQ",
        "Postman Colletion Testing",
    ],
    BuildTools: [
        "NPM",
        "Vite",
        "Yarn",
        "Github Actions",
        "esLint",
        "Nuget",
        "Webpack",
        "Gulp",
        "CRA",
        "Oracle SOA Suite",
        "NextJS",
    ],
    DeploymentTools: [
        "Azure",
        "AWS (Amazon Web Services)",
        "Docker",
        "Kubernetes",
        "Vercel",
        "Digital Ocean",
        "Jenkins",
    ],
    Architectures: ["REST", "SOAP", "YAML", "WSDL", "BPEL"],
    ProjectTools: [
        "Azure DevOps",
        "Azure UAT",
        "Figma",
        "Chrome Developer Tools",
        "JIRA",
        "Trello",
        "Cypress.io",
    ],
    Methodologies: ["CI/CD", "Agile", "Scrum", "Data Structures", "Algorithms"],
    MonitoringTools: ["Splunk", "Dynatrace", "ELK", "DataDog"],
    ThirdPartyApis: [
        "Auth0",
        "Google Maps",
        "Nodemailer",
        "Cloudinary",
        "Stripe",
        "OpenAI",
    ],
};
